import Head from 'next/head'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { Auth } from '@supabase/auth-ui-react'
import {
    // Import predefined theme
    ThemeSupa,
  } from '@supabase/auth-ui-shared'
import TodoList from '@/components/TodoList'
import Header from '@/components/Header'

// cd /mnt/c/Users/cmulholla/Desktop/Programming/bun/SP2/Supabase-Next-Ex/

export default function Home() {
  const session = useSession()
  const supabase = useSupabaseClient()

  return (
    <>
      <Header session={session} supabase={supabase}/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full bg-gray-200">
        {!session ? (
          <div className="min-w-full min-h-screen flex items-center justify-center">
            <div className="w-full h-full flex justify-center items-center p-4">
              <div className="w-full h-full sm:h-auto sm:w-2/5 max-w-sm p-5 bg-white shadow flex flex-col text-base">
                This amazing website is powered by Supabase, ReactJS, NextJS, TailwindCSS, Bun, AWS, and Mistral.
                Sign up or log in to get started!
              </div>
            </div>
          </div>
        ) : (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{ minWidth: 250, maxWidth: 600, margin: 'auto' }}
          >
            {
              /* send the user to the dashboard if they are logged in 
              <TodoList session={session} />
              */
              window.location.href = `/dashboard`
            }
          </div>
        )}
      </div>
    </>
  )
}